### ISSUE TITLE
Can't refresh action runner group

### ISSUE THREAD

**Issue by AleksandrAksenov** [pulumi/pulumi-github#323]
### What happened?

I get the error when i try to run:
```
pulumi refresh
```
The error is:
```
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x2 addr=0x48 pc=0x102f73ecc]
    goroutine 81 [running]:
    github.com/integrations/terraform-provider-github/v5/github.resourceGithubActionsRunnerGroupRead(0x14000320460, {0x103904740?, 0x14000888ac0?})
    	/home/runner/go/pkg/mod/github.com/integrations/terraform-provider-github/v5@v5.18.0/github/resource_github_actions_runner_group.go:203 +0x72c
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Refresh(0x140009d7860, 0x140000aae60, {0x103904740, 0x14000888ac0})
    	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:526 +0x1cc
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Refresh(0x140001e6e80, 0x140008d34c0, 0x1b?)
    	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:333 +0x60
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v1.v1Provider.Refresh({0x14000959290?}, {0x1034304cc?, 0x140009d7860?}, {0x103c344d8?, 0x14000801e00?})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.40.0/pkg/tfshim/sdk-v1/provider.go:102 +0x78
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Read(0x140009d8a00, {0x103c332e8?, 0x140008fc7b0?}, 0x140001a37a0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.40.0/pkg/tfbridge/provider.go:980 +0x4b0
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler.func1({0x103c332e8, 0x140008fc7b0}, {0x103b37720?, 0x140001a37a0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.53.1/proto/go/provider_grpc.pb.go:591 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x103c332e8, 0x140008fc2d0}, {0x103b37720, 0x140001a37a0}, 0x14000808320, 0x140007fc570)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30c
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler({0x103bde640?, 0x140009d8a00}, {0x103c332e8, 0x140008fc2d0}, 0x140003201c0, 0x14000992b20)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.53.1/proto/go/provider_grpc.pb.go:593 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0x140002d63c0, {0x103c3aa20, 0x140004c8340}, 0x1400033ac60, 0x14000435770, 0x1047a9378, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1340 +0xb7c
    google.golang.org/grpc.(*Server).handleStream(0x140002d63c0, {0x103c3aa20, 0x140004c8340}, 0x1400033ac60, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1713 +0x82c
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:965 +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:963 +0x290
```

### Expected Behavior

Pulumi should refresh the state

### Steps to reproduce

* Create an action runner group on GitHub
* Import the action runner group
* Run `pulumi up`
* Run `pulumi refesh`

### Output of `pulumi about`

```CLI
Version      3.57.1
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.31.0
github      5.5.0
hcloud      1.10.3
kubernetes  3.24.1
python      unknown
random      4.12.0

Host
OS       darwin
Version  11.7.4
Arch     arm64

This project is written in python: executable='/Users//.pyenv/shims/python3' version='3.10.8
'

Current Stack: actionrunnergroups.prod

TYPE                                                URN
pulumi:pulumi:Stack                                 urn:pulumi:actionrunnergroups.prod::actionrunnergroups::pulumi:pulumi:Stack::actionrunnergroups-actionrunnergroups.prod
pulumi:providers:pulumi                             urn:pulumi:actionrunnergroups.prod::actionrunnergroups::pulumi:providers:pulumi::default
pulumi:pulumi:StackReference                        urn:pulumi:actionrunnergroups.prod::actionrunnergroups::pulumi:pulumi:StackReference::repositories.prod
pulumi:providers:github                             urn:pulumi:actionrunnergroups.prod::actionrunnergroups::pulumi:providers:github::default_5_5_0
github:index/actionsRunnerGroup:ActionsRunnerGroup  urn:pulumi:actionrunnergroups.prod::actionrunnergroups::github:index/actionsRunnerGroup:ActionsRunnerGroup::action-runner-group-build
github:index/actionsRunnerGroup:ActionsRunnerGroup  urn:pulumi:actionrunnergroups.prod::actionrunnergroups::github:index/actionsRunnerGroup:ActionsRunnerGroup::action-runner-group-test
github:index/actionsRunnerGroup:ActionsRunnerGroup  urn:pulumi:actionrunnergroups.prod::actionrunnergroups::github:index/actionsRunnerGroup:ActionsRunnerGroup::action-runner-group-Default
github:index/actionsRunnerGroup:ActionsRunnerGroup  urn:pulumi:actionrunnergroups.prod::actionrunnergroups::github:index/actionsRunnerGroup:ActionsRunnerGroup::action-runner-group-demo
github:index/actionsRunnerGroup:ActionsRunnerGroup  urn:pulumi:actionrunnergroups.prod::actionrunnergroups::github:index/actionsRunnerGroup:ActionsRunnerGroup::action-runner-group-prod


Found no pending operations associated with actionrunnergroups.prod

Backend
Name           LAPTOP_NAME
URL            s3://pulumigithub?endpoint=server:9000&s3ForcePathStyle=true&profile=miniogithub&region=eu-central-1
User           user
Organizations

Dependencies:
NAME               VERSION
boto3              1.26.89
pip                23.0.1
pulumi-aws         5.31.0
pulumi-github      5.5.0
pulumi-hcloud      1.10.3
pulumi-kubernetes  3.24.1
pulumi-policy      1.5.0
pulumi-random      4.12.0
setuptools         65.4.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aq17** [comment]
Hi @AleksandrAksenov , thanks for opening this issue. It looks like this is a known bug in the upstream provider:
- https://github.com/integrations/terraform-provider-github/issues/1524
- https://github.com/integrations/terraform-provider-github/issues/1553
